name: Test

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.11.1

      - name: Show Node version
        run: node --version

      - name: Show NPM version
        run: npm --version

      - name: Show repository files
        run: ls -la

      - name: Install API dependencies
        working-directory: api
        run: npm ci

      - name: Show installed packages
        working-directory: api
        run: npm list --depth=0

      - name: Install Frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Show installed packages
        working-directory: frontend
        run: npm list --depth=0

      - name: Build frontend
        working-directory: frontend
        run: npm run build
